# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7f7b34b33f8fbd526665408071f75ad8e5de2e44a6db4b730bbcbd17459d03af8f99d68d2673d5a2672354c133cc95eca79f889e0ed84a9cb5d5d2d03bfeea39

test:
  secret_key_base: 1a40cdd947fd014d5c71ac03fabc8d6177c93ecc703bcc8506fd233668e572f1c45a1ed5d01c086dde4868c1959356dfe7efea39c2a824993e505eca3cdd798b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
